### ISSUE TITLE
Evaluation with odometry.bag

### ISSUE THREAD

**Issue by wwtinwhu** [NeBula-Autonomy/LOCUS#52]
Thank you for the excellent work your team has done! @BenjaminMorrell @femust . How to quickly get the evaluation result of trajectory APE using the odometry.bag (GT) and  odometry.bag obtained by LOCUS? Is there anything to watch out for? Such as time alignment or coordinate transformation.

**Comment by femust** [comment]
you can use [evo](https://github.com/MichaelGrupp/evo) or our [localization_analyzer](https://github.com/NeBula-Autonomy/localization_analyzer) based on evo. Though the documentation of our localizer is not yet fully finished as far as I remember. 

Remember that your trajectory should have init configuration that bases on "fiducial calibration" (see extra_files in our odometry dataset). So this ${robot}_fiducial_calibration should be your first pose. But if you started from "0" then probably you need to just transform the trajectory (poses) by the transformation matrix based on this fiducial calibration.

Or the easiest/laziest way is to use flag --align in evo (but there are some caviats of this method and you can miss some important information from your data).

**Comment by wwtinwhu** [comment]
> you can use [evo](https://github.com/MichaelGrupp/evo) or our [localization_analyzer](https://github.com/NeBula-Autonomy/localization_analyzer) based on evo. Though the documentation of our localizer is not yet fully finished as far as I remember.
> 
> Remember that your trajectory should have init configuration that bases on "fiducial calibration" (see extra_files in our odometry dataset). So this ${robot}_fiducial_calibration should be your first pose. But if you started from "0" then probably you need to just transform the trajectory (poses) by the transformation matrix based on this fiducial calibration.
> 
> Or the easiest/laziest way is to use flag --align in evo (but there are some caviats of this method and you can miss some important information from your data).

Thanks! @femust .  I used localization_analyzer. Firstly, I used LOCUS to run the 6_Husky4_Tunnel_EX2 sequence. However, the evaluation result is not good as in paper. I used tmuxp load run_analyzer.yaml to easily evaluate. This is one of the results：
![image](https://user-images.githubusercontent.com/28035224/188262831-1240f1b8-0601-4f09-9ab2-23783b4309d4.png)
Where did I go wrong?

**Comment by femust** [comment]
hmm can you show the xyz trajectory?
Something like this
![image](https://user-images.githubusercontent.com/26916586/188263344-5203b002-32bd-4695-82d6-7f970945f165.png)

(this is one of many experiments that I did so it may differ from yours), what mapping technique do you use?

**Comment by wwtinwhu** [comment]
@femust  I used LOCUS.  It is so weird. The odometry.bag obtained by LOCUS is normal when I visualize it in Rviz. However, the comparion result is like this. 
![image](https://user-images.githubusercontent.com/28035224/188300010-d31cf04b-2ec0-4178-88d5-378420643ab5.png)

**Comment by femust** [comment]
It seems that locus that you run is in one position :) maybe some crash, do you see the visualization in rviz?
Just for clarification you should run bag file run locus and record topic ```rosbag record -t /robot_name/locus/odometry``` and this you can compare to odometry.bag

**Comment by wwtinwhu** [comment]
> It seems that locus that you run is in one position :) maybe some crash, do you see the visualization in rviz? Just for clarification you should run bag file run locus and record topic `rosbag record -t /robot_name/locus/odometry` and this you can compare to odometry.bag

I find the problem. The odometry.bag is right. However, the aggregated_odometries.bag dervied by analyzer.py is not right.

**Comment by wwtinwhu** [comment]
> It seems that locus that you run is in one position :) maybe some crash, do you see the visualization in rviz? Just for clarification you should run bag file run locus and record topic `rosbag record -t /robot_name/locus/odometry` and this you can compare to odometry.bag
Hi @femust  
https://github.com/NeBula-Autonomy/localization_analyzer/blob/899b7ff4904cceace37449f61a896474d31abdf1/utilities/aggregate_odometries.py#L76 
It should be                 d[key][1] =  list(bag.get_type_and_topic_info()[1].keys())[3] , so that locus/odometry msg can be aggregated to the final bag.  The updated result is like that. What issues need to be taken care of to get close to the results in the paper?
![image](https://user-images.githubusercontent.com/28035224/188300914-b0aa033b-a149-40d1-bf0c-c9246ad153d1.png)
![image](https://user-images.githubusercontent.com/28035224/188300922-e582b823-9bda-47c2-9823-d40dd8ef8318.png)

**Comment by femust** [comment]
You can also try different mappers from [here](https://github.com/NeBula-Autonomy/LOCUS/blob/main/locus/config/lo_settings.yaml#L56) for better results [ikdtree, mapper (based on octree) -> memory constrains]

Btw you can limit the run of your system to 18500 s since the ground truth is done only for this period (see gt end time).

Regarding your plots, the results on my end look similar:
![image](https://user-images.githubusercontent.com/26916586/188301332-578327a1-c2f5-4f65-8dfa-726aeb2288f0.png)

![image](https://user-images.githubusercontent.com/26916586/188301364-309937ce-2e7a-4446-93a7-7dd530875eb9.png)

This one is done for adaptive voxelization 3k points, ikdtree  (by default our open source solution uses multi-threaded octree)
![image](https://user-images.githubusercontent.com/26916586/188301418-2b3a3d91-fd2a-423b-83a4-24ac920bcbda.png)

here are the trajectories across a different number of points and ikdtree
![image](https://user-images.githubusercontent.com/26916586/188301442-d6f260cd-998d-4eed-a9ed-f63c0780229d.png)

(10k fails due to a large amount of CPU burden at some point, especially where there are some limitations of observability), so it's better to keep the number of points on small level (e.g. 3k). Different SLAM/lidar odometry approaches just use voxel with large size and for most datasets is enough but here we want to adapt to the environment to keep a number of points similar (so we change voxel size dynamically).

Hope this helps!

**Comment by wwtinwhu** [comment]
Thank you for your patience and very prompt answer! @femust  That's really help!
